[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/shop/:slug"
  to = "/storefront/index.html?slug=:slug"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard/index.html"
  status = 200

[[redirects]]
  from = "/store"
  to = "/storefront/index.html"
  status = 200
